HelpInfo,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:EDIB_CMD
Implementation;Synthesis|| CS153 ||@E:Can't mix blocking and non-blocking assignments to a variable||EDIB_CMD.srr(28);liberoaction://cross_probe/hdl/file/'D:\M2S010TQG144\EDIB_1\EDIB_CMD\EDIB_CMD\synthesis\EDIB_CMD.srr'/linenumber/28||EDIB_CMD.v(52);liberoaction://cross_probe/hdl/file/'D:\M2S010TQG144\EDIB_1\EDIB_CMD\EDIB_CMD\hdl\EDIB_CMD.v'/linenumber/52
