HelpInfo,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\lib\html,fpgahelp.qhc,errormessages.mp,C:\Microsemi\Libero_SoC_v11.8\SynplifyPro\bin\mbin\assistant
Implementation;Synthesis;RootName:EDIB_M2
Implementation;Synthesis|| CS153 ||@E:Can't mix blocking and non-blocking assignments to a variable||EDIB_M2.srr(28);liberoaction://cross_probe/hdl/file/'D:\M2S010TQG144\EDIB_1\EDIB_M2\EDIB_M2\synthesis\EDIB_M2.srr'/linenumber/28||EDIB_M2.v(50);liberoaction://cross_probe/hdl/file/'D:\M2S010TQG144\EDIB_1\EDIB_M2\EDIB_M2\hdl\EDIB_M2.v'/linenumber/50
